services:
  - type: web
    name: edugenie-chatbot
    env: python
    pythonVersion: 3.13.12
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: GROQ_API_KEY
        value: ""
